package com.royportas.elastic_importer;

import java.io.IOException;
import java.io.File;
import java.lang.Exception;
import com.beust.jcommander.*;

class Args {
    @Parameter(
        names={"--csv"},
        description="The CSV file to process",
        required=true
    )
    String csvFilename;

    @Parameter(
        names={"--index", "-i"},
        description="The name of the elasticsearch index"
    )
    String indexName;
}

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] argv) throws IOException, Exception {
        Args args = new Args();

        JCommander.newBuilder()
            .addObject(args)
            .build()
            .parse(argv);

        if (!App.exists(args.csvFilename)) {
            System.err.println("csv path is incorrect");
            System.exit(1);
        }

        Elastic elastic;

        // Start the Elastic client
        try {
            elastic = new Elastic();
            elastic.createIndex();
            elastic.setMapping();

            NProbe nprobe = new NProbe();
            nprobe.parse(args.csvFilename, elastic);

            elastic.close();
        } catch (Exception e) {
            System.err.println(e.getMessage());
            System.exit(1);
        }

    }

    public static Boolean exists(String filename) {
        return new File(filename).isFile();
    }
}
